# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "nvme" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/b191e62c-e033-428d-bb53-bcf9f27d823d";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-3206a820-66a6-4812-ab89-8e44fe35e2f6".device = "/dev/disk/by-uuid/3206a820-66a6-4812-ab89-8e44fe35e2f6";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/BC8E-A07E";
      fsType = "vfat";
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/979631ab-3cb1-4d10-abab-c00547768902"; }
    ];

boot.resumeDevice = "/dev/disk/by-uuid/979631ab-3cb1-4d10-abab-c00547768902";
boot.kernelParams = [ "mem_sleep_default=deep" ];


  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp0s20f3.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  powerManagement.cpuFreqGovernor = lib.mkDefault "powersave";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
