# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [
      (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "nvme" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    {
      device = "/dev/disk/by-uuid/53dc9fd2-067e-454f-911b-e0df8a367050";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-716f0439-bc21-45f0-864b-2cc2951e5148".device = "/dev/disk/by-uuid/716f0439-bc21-45f0-864b-2cc2951e5148";

  fileSystems."/boot/efi" =
    {
      device = "/dev/disk/by-uuid/A4AE-38C7";
      fsType = "vfat";
    };

  swapDevices = [
    { device = "/swapfile"; }
  ];

  boot.resumeDevice = "/dev/disk/by-uuid/53dc9fd2-067e-454f-911b-e0df8a367050";
  boot.kernelParams = [ "mem_sleep_default=deep" "resume_offset=49123328" ];


  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp0s20f3.useDHCP = lib.mkDefault true;

  powerManagement.cpuFreqGovernor = lib.mkDefault "powersave";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
  # high-resolution display
  # hardware.video.hidpi.enable = lib.mkDefault true;
}
