# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "nvme" "usb_storage" "uas" "sd_mod" "sr_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/57cc7e6a-b72e-4720-80c1-8fa50ca5dbc6";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-7bd094fc-2d0a-4ea7-a75e-9dd64b62e0fa".device = "/dev/disk/by-uuid/7bd094fc-2d0a-4ea7-a75e-9dd64b62e0fa";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/BC8E-A07E";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/979631ab-3cb1-4d10-abab-c00547768902"; }
    ];

  boot.resumeDevice = "/dev/disk/by-uuid/979631ab-3cb1-4d10-abab-c00547768902";
  boot.kernelParams = [ "mem_sleep_default=deep" ];


  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp0s20f3.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  powerManagement.cpuFreqGovernor = lib.mkDefault "powersave";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
