import = [ "~/.config/alacritty/dark.toml" ]

[font]
normal = { family = "CaskaydiaCove Nerd Font", style = "Book" }
bold = { family = "CaskaydiaCove Nerd Font", style = "Bold" }
italic = { family = "CaskaydiaCove Nerd Font", style = "Italic" }
bold_italic = { family = "CaskaydiaCove Nerd Font", style = "Bold Italic" }
size = 11

[cursor] 
style = { shape = "Underline" }
vi_mode_style = "Block"
unfocused_hollow = true

[mouse]
hide_when_typing = true

[window]
opacity = 0.9

[env]
TERM = "xterm-256color"
